version: 1
accounts:
  - name: alice
    coins:
      - 1000000000ustake
      - 100000000000000000000stake
  - name: bob
    coins:
      - 1000000000stake
genesis:
  app_state:
    crisis:
      constant_fee:
        denom: stake
    gov:
      deposit_params:
        min_deposit:
          - amount: "10000"
            denom: stake
    mint:
      params:
        mint_denom: stake
    staking:
      params:
        bond_denom: stake
validators:
- name: alice
  bonded: 1000000stake