version: '3'

services:
  covennode0:
    container_name: covennode0
    image: mage-war/coven:latest
    ports:
    - "26656-26657:26656-26657"
    volumes:
    - ./build:/home
    command: /bin/sh -c 'cd /home/nodecluster/node0 && coven start --home coven'
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  covennode1:
    container_name: covennode1
    image: mage-war/coven:latest
    ports:
    - "26659-26660:26656-26657"
    volumes:
    - ./build:/home
    command: /bin/sh -c 'cd /home/nodecluster/node1 && coven start --home coven'
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  covennode2:
    container_name: covennode2
    image: mage-war/coven:latest
    ports:
    - "26661-26662:26656-26657"
    volumes:
    - ./build:/home
    command: /bin/sh -c 'cd /home/nodecluster/node2 && coven start --home coven'
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  covennode3:
    container_name: covennode3
    image: mage-war/coven:latest
    ports:
    - "26663-26664:26656-26657"
    volumes:
    - ./build:/home
    command: /bin/sh -c 'cd /home/nodecluster/node3 && coven start --home coven'
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16
